language: c

sudo: false

branches:
  except:
    - /^*-v[0-9]/
    - /^build-[0-9a-z\-]*/

notifications:
  email: false

cache:
  apt: true
  directories:
  - "/home/travis/devkitPro"

before_cache:
- rm -rf $DEVKITPRO/*.7z
- rm -rf $DEVKITPRO/*.bz2
- rm -rf $DEVKITPRO/examples

addons:
  apt:
    packages:
    - p7zip-full
    - zip

before_install:
- export DEVKITPRO=/home/travis/devkitPro
- export DEVKITPPC=${DEVKITPRO}/devkitPPC
- mkdir -p $DEVKITPRO
- cd $DEVKITPRO
- wget -N http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitPPCupdate.pl
- wget -N https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/libogc.7z
- wget -N https://github.com/dimok789/loadiine_gx2/releases/download/v0.2/portlibs.7z

install:
- cd $DEVKITPRO
- perl devkitPPCupdate.pl
- 7z x -y libogc.7z
- 7z x -y portlibs.7z
- cp -R portlibs/ppc/* devkitPPC/

before_script:
- cd $TRAVIS_BUILD_DIR/

script:
- make
- cd $TRAVIS_BUILD_DIR/installer
- make

before_deploy:
- cd $TRAVIS_BUILD_DIR/
- cp -R installer/bin/*.bin www/loadiine_gx2/
- commit="$(git rev-parse --short=7 HEAD)"
- zip -r loadiine_gx2_$commit.zip www loadiine_gx2.elf
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=Loadiine-nightly-$commit
- git tag $GIT_TAG -a -m "Loadiine_gx2 nightly build. Not a stable release. Expect bugs!"
- git push --quiet https://$GITHUBKEY@github.com/dimok789/loadiine_gx2 $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
    secure: R7WrOSmjYSD3DfUyUkklxSheD7MU/np6MycSJ11B1CZ054FUz+xMY5WlvM7mjoq8YDYSznKtRmoFEmc1ZQW/hFNZORPjTvLDOeO/8KWP+RmFS2VKFgpEYn6oBFnFWfzRcLelLcYIuJoCgqEB0NcUSXR1NNvpp4KIszdoO8bJlJekNcwnnUCjeYSRT0JcP5RFqCZoVex6YREgmJfe3mJ0/B8gFgHkwQeQpIS7WVDfC6EgEL5bXLCZuVwGQzyqG6rTvkxVVG/vXeKvFOKZJQbY78l09KlU31WU7Kql6mMwuq7cUXkDwczt2iO/cxAaUQnJ4KDmWCDuiJugCXyFMnAyOdAJvGu5WvN2S4aGzxmxqopKoW0wAHf1L+Juv9z36FrYlmT3iYS1KBzM6jVjj2+Bev9xPJuEpRFgvKJI0JlyqX9bXnhF4rOnIaNUEn41EkRGPcYDS4cGsVqNL+CsuND0YGmRw4hOo3E69Oex1WEBMwZNohb8CfVBNXY9I3i6qe4rJ0LJsfsYykK5j1Hc9ZWJpLZQNZHr3gOS3alFq3A4Jwad0yynxkbGML6TUxYcz0TRqoKE1FMrpL2UgyZhG2I3ugH9q3GPF/50CCBEsuVvCwgar9Y0Yw4q/MQwmgX7gg8jaeydS/pAoFcf1MMews57+cL9qiEGKiIL3glp55eNP4Y=
  file: loadiine_gx2_$commit.zip
  on:
    repo: dimok789/loadiine_gx2
    tags: false
    all_branches: true